name: Go

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set up PDFium library
        run: |
          sudo curl -L https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F4849/pdfium-linux-x64.tgz -o pdfium-linux-x64.tgz && sudo mkdir /opt/pdfium && sudo tar -C /opt/pdfium -xvf pdfium-linux-x64.tgz
          sudo rm pdfium-linux-x64.tgz
          sudo cp ./.github/workflows/pdfium.pc /usr/lib/pkgconfig/pdfium.pc

      - name: Test all packages
        run: |
          export LD_LIBRARY_PATH="/opt/pdfium/lib"
          go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Test implementation for coverage
        run: |
          export LD_LIBRARY_PATH="/opt/pdfium/lib"
          go test ./internal/implementation -coverprofile=coverage.out -covermode=atomic

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./coverage.out
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.out
